version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - food-order-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - food-order-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - food-order-network

networks:
  food-order-network:
    driver: bridge

volumes:
  mongo-data:

